<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Pulindu Pansilu | Creative Genius Portfolio</title>
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;600&display=swap" rel="stylesheet">
  <style>
    * {
      box-sizing: border-box;
    }
    body {
      font-family: 'Outfit', sans-serif;
      margin: 0;
      background-color: #0e0e0e;
      color: #e0e0e0;
    }
    header {
      background: linear-gradient(135deg, #111, #222);
      padding: 80px 20px 40px;
      text-align: center;
    }
    .profile-container {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 20px;
      animation: fadeIn 1.5s ease-in-out;
    }
    .profile-photo {
      width: 120px;
      height: 120px;
      border-radius: 50%;
      object-fit: cover;
      border: 3px solid #1db954;
      animation: popIn 1.2s ease-in-out;
    }
    @keyframes fadeIn {
      0% { opacity: 0; transform: translateY(-20px); }
      100% { opacity: 1; transform: translateY(0); }
    }
    @keyframes popIn {
      0% { transform: scale(0.5); opacity: 0; }
      100% { transform: scale(1); opacity: 1; }
    }
    header h1 {
      font-size: 3em;
      margin: 0;
    }
    header p {
      margin-top: 10px;
      font-size: 1.2em;
      color: #bbb;
    }
    nav {
      display: flex;
      justify-content: center;
      background-color: #1b1b1b;
      padding: 10px 0;
      gap: 30px;
    }
    nav a {
      color: #fff;
      text-decoration: none;
      padding: 10px;
      font-weight: 600;
      transition: color 0.3s ease;
    }
    nav a:hover {
      color: #1db954;
    }
    section {
      padding: 60px 20px;
      max-width: 1200px;
      margin: auto;
    }
    section h2 {
      border-left: 5px solid #1db954;
      padding-left: 15px;
      margin-bottom: 30px;
      font-size: 2em;
      color: #fff;
    }
    .intro {
      text-align: center;
      max-width: 800px;
      margin: 0 auto 60px;
      font-size: 1.1em;
      color: #ccc;
      line-height: 1.6em;
      animation: fadeIn 1.5s ease-in-out;
    }
    .social-links {
      display: flex;
      justify-content: center;
      gap: 20px;
      margin-top: 30px;
    }
    .social-links a {
      color: #1db954;
      text-decoration: none;
      font-weight: 600;
      border: 1px solid #1db954;
      padding: 8px 14px;
      border-radius: 5px;
      transition: background-color 0.3s, color 0.3s;
    }
    .social-links a:hover {
      background-color: #1db954;
      color: #000;
    }
    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
      gap: 25px;
    }
    .project {
      background-color: #181818;
      border: 1px solid #333;
      border-radius: 10px;
      overflow: hidden;
      padding: 20px;
      transition: transform 0.3s ease;
    }
    .project:hover {
      transform: translateY(-5px);
    }
    .project h3 {
      color: #1db954;
      margin-top: 0;
    }
    .project p {
      color: #ccc;
    }
    .project-media {
      margin-bottom: 15px;
    }
    .project-media img,
    .project-media video {
      width: 100%;
      border-radius: 6px;
    }
    footer {
      background-color: #111;
      text-align: center;
      padding: 30px 20px;
      color: #777;
      font-size: 0.9em;
    }
  </style>
</head>
<body>
  <header>
    <div class="profile-container">
      <img src="https://via.placeholder.com/120" alt="Profile Photo" class="profile-photo">
      <h1>Pulindu Pansilu</h1>
      <p>Writer | Editor | Director | Creative Genius</p>
    </div>
  </header>

  <nav>
    <a href="#home">Home</a>
    <a href="#directing">Filmography</a>
    <a href="#editing">Editing Showcase</a>
  </nav>

  <section id="home">
    <h2>About Me</h2>
    <div class="intro">
      <p>Hi, I’m Pulindu Pansilu — a multidisciplinary filmmaker who thrives on crafting powerful visual stories. With a deep-rooted passion for storytelling, I’ve directed thought-provoking short films, edited impactful commercial content, and written scripts that challenge conventions. I believe in pushing creative boundaries and bringing raw ideas to life through bold visuals and authentic emotion. This is not just a portfolio, it’s a reflection of a creative genius at work.</p>
      <div class="social-links">
        <a href="mailto:your.email@example.com">Email</a>
        <a href="https://www.instagram.com/yourhandle" target="_blank">Instagram</a>
        <a href="https://www.linkedin.com/in/yourprofile" target="_blank">LinkedIn</a>
        <a href="https://github.com/yourgithub" target="_blank">GitHub</a>
      </div>
    </div>
  </section>

  <section id="directing">
    <h2>Filmography</h2>
    <div class="grid">
      <div class="project">
        <div class="project-media">
          <video controls poster="https://via.placeholder.com/600x340?text=Unfinished+Prayer">
            <source src="your-video-url.mp4" type="video/mp4">
            Your browser does not support the video tag.
          </video>
        </div>
        <h3>Unfinished Prayer</h3>
        <p>A haunting psychological drama directed and written by Pulindu Pansilu, shot across a graveyard, church, and cursed house.</p>
      </div>
      <div class="project">
        <div class="project-media">
          <img src="https://via.placeholder.com/600x340?text=Sweep+Short+Film" alt="Sweep Thumbnail">
        </div>
        <h3>Sweep</h3>
        <p>A surreal thriller about a teen boy’s descent into madness after winning a massive lottery ticket. Directed by Pulindu Pansilu.</p>
      </div>
    </div>
  </section>

  <section id="editing">
    <h2>Editing Showcase</h2>
    <div class="grid">
      <div class="project">
        <div class="project-media">
          <video controls poster="https://via.placeholder.com/600x340?text=Urban+Brew">
            <source src="your-video-url.mp4" type="video/mp4">
            Your browser does not support the video tag.
          </video>
        </div>
        <h3>Urban Brew</h3>
        <p>High-energy promotional video for a coffee startup launch. Edited by Pulindu Pansilu with cinematic color grading and rhythmic pacing.</p>
      </div>
      <div class="project">
        <div class="project-media">
          <img src="https://via.placeholder.com/600x340?text=Mobile+Mug+Promo" alt="Mobile Mug Promo">
        </div>
        <h3>Mobile Mug Promo</h3>
        <p>Narrative-driven commercial edit for a mobile coffee shop. Blends motion graphics with handheld aesthetics to boost engagement.</p>
      </div>
    </div>
  </section>

  <footer>
    <p>© 2025 Pulindu Pansilu. All rights reserved. | Built by a Creative Genius.</p>
  </footer>
</body>
</html>

